services: 
  frontend:
    build: 
      dockerfile: ../docker/frontend/Dockerfile
      context: ./frontend
    ports: 
     - "3000:3000"
  server:
    build: 
      dockerfile: ../docker/server/Dockerfile
      context: ./server
    ports: 
     - "9000:9000"
  db: 
    image: postgres:16.2-alpine3.19 
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
