services: 
  findfirst-frontend:
    build: 
      dockerfile: ../docker/frontend/Dockerfile
      context: ./frontend
    ports: 
     - "8080:8080"
  findfirst-server:
    build: 
      dockerfile: ../docker/server/Dockerfile
      context: ./server
    ports: 
     - "9000:9000"
  db: 
    image: postgres:16.2-alpine3.19 
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  mail: 
    image: mailhog/mailhog:latest
    ports: 
      - 1025:1025
      - 8025:8025
