name: Deploy
on: 
  push:
    branches:
      - main
jobs:
  build:
    - name: Re-Deploy Docker
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: ./FindFirst/deploy/deploy.sh
